import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'
import { Data } from './api/users'

export default function Home() {

  const [data, setData] = useState<Data>()

  useEffect(() => {
    if (!data) {
      load()
    }
  }, [])

  const load = async (page = 0) => {
    const { data } = await axios.get(`/api/users`, { params: { page } })
    setData(data)
  }    

  return (
    <div className={styles.container}>
      <Head>
        <title>Usuários</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lista de <span>Usuários</span>
        </h1>
  
        <p className={styles.description}>
          <code className={styles.code}>pagina {data?.page} de {data?.total_pages}</code>
        </p>

        <div className={styles.list}>
          
          {data?.data.map(el => (
            <div key={el.id} className={styles.card}>
              <Image 
                className="avatar"
                loader={() => el.avatar}
                src="me.png"
                alt="Picture of the author"
                width={75}
                height={75}
              />
              <div>
                <h2>{el.first_name} {el.last_name}</h2>
                <p>{el.email}</p>
              </div>
            </div>
          ))}

        </div>
      </main>

      {(data?.page && data?.total_pages) && (
      <footer className={styles.footer}>
        {data.page > 1 && (
          <a onClick={() => load(data.page - 1)}>
            &larr; Anterior 
          </a>
        )}
        {data.page < data.total_pages && (
          <a onClick={() => load(data.page + 1)}>
            Próximo &rarr;
          </a>
        )}
      </footer>
      )}

    </div>
  )
}
